In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns
from tqdm import tqdm
from scipy.sparse import load_npz
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import fbeta_score, accuracy_score, precision_score, recall_score
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

## Loading the data

In [3]:
train_data = pd.read_csv('./data/processed/train_set.txt').set_index('Unnamed: 0')
train_data
valid_data = pd.read_csv('./data/processed/valid_set.txt').set_index('Unnamed: 0')
test_data = pd.read_csv('./data/processed/test_set.txt').set_index('Unnamed: 0')
valid_data
test_data
tfidf_features = load_npz('./data/processed/tfidf_features.npz')
tfidf_features

seq_id  medline_ui  \
Unnamed: 0                       
55655        54711    88006849   
277600       54711    91012901   
172713       54711    89248820   
277300       54711    91011780   
132901       54711    89372453   
...            ...         ...   
125350       54711    88298584   
271319       54711    90225099   
137903       54711    89297385   
153639       54711    89268911   
127517       54711    89327649   

                                                   mesh_terms  \
Unnamed: 0                                                      
55655       Adult; Aged; Attitude of Health Personnel/*; A...   
277600      Allergy and Immunology/*; Human; Hypersensitiv...   
172713      Administration, Oral; Adult; Aged; Chronic Dis...   
277300      Case Report; Female; Hemangioma/*PA; Human; Le...   
132901            Delirium/*/ET; Human; Surgery, Operative/*.   
...                                                       ...   
125350      Acetazolamide/*PD; Acid-Base Equilibrium/*DE; ...   
271319      Animal; Antibodies, Monoclonal; Antigens, Diff...   
137903      Adult; Amnesia/*CI/ET; Case Report; Cerebral A...   
153639      Amino Acids, Branched-Chain/*TU; Human; Parent...   
127517      Biopsy; Case Report; Elastic Tissue/PA; Granul...   

                                             publication_type  \
Unnamed: 0                                                      
55655                                        JOURNAL ARTICLE.   
277600                                                  NEWS.   
172713                                       JOURNAL ARTICLE.   
277300      JOURNAL ARTICLE; REVIEW; REVIEW OF REPORTED CA...   
132901                                       JOURNAL ARTICLE.   
...                                                       ...   
125350                                       JOURNAL ARTICLE.   
271319                                       JOURNAL ARTICLE.   
137903                                       JOURNAL ARTICLE.   
153639             JOURNAL ARTICLE; REVIEW; REVIEW, TUTORIAL.   
127517                                       JOURNAL ARTICLE.   

                                                       author  \
Unnamed: 0                                                      
55655                                 Karlik BA; Yarcheski A.   
277600                                              Cotton P.   
172713      Thirlwell MP; Sloan PA; Maroun JA; Boos GJ; Be...   
277300                                   Ragbeer MS; Stone J.   
132901                                           Golinger RC.   
...                                                       ...   
125350      Bickler PE; Litt L; Banville DL; Severinghaus JW.   
271319      Steiniger B; Schroder D; Luck R; Luciano L; va...   
137903                                     Giang DW; Kido DK.   
153639                                   Teasley KM; Buss RL.   
127517                             Kato H; Uyeki Y; Yaoita H.   

                                                 source  sensitive  \
Unnamed: 0                                                           
55655                     Heart Lung 8801; 16(5):544-51          0   
277600                    JAMA 9101; 264(17):2184, 2187          0   
172713                Cancer 8909; 63(11 Suppl):2275-83          0   
277300       J Oral Maxillofac Surg 9101; 48(10):1113-7          0   
132901                       Am Surg 8912; 55(9):549-51          0   
...                                                 ...        ...   
125350                 J Appl Physiol 8811; 65(1):422-7          0   
271319                  Am J Pathol 9007; 136(4):967-78          0   
137903                     Radiology 8910; 172(1):195-6          0   
153639                           DICP 8909; 23(5):411-6          0   
127517      J Am Acad Dermatol 8911; 21(2 Pt 2):398-400          0   

            relevance_status  \
Unnamed: 0                     
55655                    NaN   
277600                  

seq_id  medline_ui  \
Unnamed: 0                       
55514        54711    88005219   
12580            1    87155935   
26334            1    87275123   
95859        54711    88282905   
212429       54711    90089954   
...            ...         ...   
279024       54711    91020534   
80895        54711    88160770   
294331       54711    91093899   
129046       54711    89340252   
161388       54711    89133651   

                                                   mesh_terms  \
Unnamed: 0                                                      
55514       Human; Infertility, Male/*ET/PP; Male; Semen/*...   
12580       Abdomen/*SU; Adult; Aged; Cholecystectomy; Com...   
26334       Adult; Arrhythmia/*ET; Bronchogenic Cyst/CO/*R...   
95859       Aluminum/AE/*BL; Brain Diseases/*CI/DI; Compar...   
212429      Adolescence; Adult; Anus/PP/*SU; Colitis, Ulce...   
...                                                       ...   
279024      Cadaver; Comparative Study; Cyclosporins/*AE/T...   
80895       Adult; Alcohol Drinking/*; Alcohol, Ethyl/BL; ...   
294331      Anemia, Sickle Cell/*IM; Antibody Formation; B...   
129046      Airway Resistance; Animal; Biguanides/*PD; Cap...   
161388      Aged; Case Report; Female; Human; Mitral Valve...   

                            publication_type  \
Unnamed: 0                                     
55514                                LETTER.   
12580                       JOURNAL ARTICLE.   
26334                       JOURNAL ARTICLE.   
95859                       JOURNAL ARTICLE.   
212429                      JOURNAL ARTICLE.   
...                                      ...   
279024      CLINICAL TRIAL; JOURNAL ARTICLE.   
80895                       JOURNAL ARTICLE.   
294331                      JOURNAL ARTICLE.   
129046                      JOURNAL ARTICLE.   
161388                               LETTER.   

                                                       author  \
Unnamed: 0                                                      
55514                                                Puri VN.   
12580                Sirinek KR; Burk RR; Brown M; Levine BA.   
26334                                Watson AJ; Chaudhary BA.   
95859       Rovelli E; Luciani L; Pagani C; Albonico C; Co...   
212429        Williams NS; Marzouk DE; Hallan RI; Waldron DJ.   
...                                                       ...   
279024      Berardinelli L; Raiteri M; Beretta C; Costanti...   
80895                                Persson J; Magnusson PH.   
294331      Marcinak JF; Frank AL; Labotka RL; Rao S; Draw...   
129046                      Haxhiu MA; Deal EC; Cherniack NS.   
161388                                             Kurnik PB.   

                                        source  sensitive  relevance_status  \
Unnamed: 0                                                                    
55514          Fertil Steril 8801; 48(4):702-3          1               NaN   
12580             Arch Surg 8706; 122(3):271-3          0               NaN   
26334                  Chest 8711; 92(2):335-6          0               NaN   
95859           Clin Nephrol 8811; 29(6):294-8          0               NaN   
212429          Br J Surg 9004; 76(11):1168-71          0               NaN   
...                                        ...        ...               ...   
279024      Transplant Proc 9101; 22(5):2343-4          0               NaN   
80895        Acta Med Scand 8806; 223(2):101-9          0               NaN   
294331            J Pediatr 9104; 118(1):69-71          0               NaN   
129046        J Appl Physiol 8911; 67(1):203-9          0               NaN   
161388        Arch Intern Med 8905; 149(2):472          0               NaN   

                                                 text_cleaned  
Unnamed: 0                                                     
55514       Smoking seminal fluid index [letter] demonstra...  
12580       Improving survival p

seq_id  medline_ui  \
Unnamed: 0                       
125              1    87049457   
153              1    87049559   
222              1    87050621   
282              1    87051243   
299              1    87051269   
...            ...         ...   
350107       54711    91368351   
350205       54711    91374975   
350206       54711    91374975   
350240       54711    91376240   
350243       54711    91376243   

                                                   mesh_terms  \
Unnamed: 0                                                      
125         Adolescence; Anesthesia, Inhalation/*AE; Child...   
153         Female; Human; Pregnancy; Propranolol/TU; Puer...   
222         Actinomycosis/*CO; Adult; Case Report; Human; ...   
282         Adult; Aged; Antineoplastic Agents, Combined/*...   
299         Adult; Aged; Autopsy; Echocardiography; Electr...   
...                                                       ...   
350107      Female; Human; Isoantibodies/AN; Pregnancy; Rh...   
350205      Antibodies/*AN; Antigenic Determinants; Blood ...   
350206      Antibodies/*AN; Antigenic Determinants; Blood ...   
350240      Child Abuse; Child Day Care Centers/*; Child, ...   
350243      Blood Glucose/AN; Diabetes Mellitus/*/BL; Exer...   

            publication_type  \
Unnamed: 0                     
125         JOURNAL ARTICLE.   
153         JOURNAL ARTICLE.   
222         JOURNAL ARTICLE.   
282         JOURNAL ARTICLE.   
299         JOURNAL ARTICLE.   
...                      ...   
350107               LETTER.   
350205      JOURNAL ARTICLE.   
350206      JOURNAL ARTICLE.   
350240      JOURNAL ARTICLE.   
350243      JOURNAL ARTICLE.   

                                                       author  \
Unnamed: 0                                                      
125                          Wark H; O'Halloran M; Overton J.   
153                                                 Ramsay I.   
222                                    McGibney D; Clarke PB.   
282             Scheid V; Buzdar AU; Smith TL; Hortobagyi GN.   
299         Wadler S; Chahinian P; Slater W; Goldman M; Me...   
...                                                       ...   
350107                                              Stroup M.   
350205                       Frampton G; Hicks J; Cameron JS.   
350206                       Frampton G; Hicks J; Cameron JS.   
350240                                 Bassoff BZ; Willis WO.   
350243                     Summerson JH; Konen JC; Dignan MB.   

                                              source  sensitive  \
Unnamed: 0                                                        
125                 Br J Anaesth 8703; 58(11):1224-8          0   
153         Br J Obstet Gynaecol 8703; 93(11):1121-3          1   
222                        Br J Urol 8703; 58(5):566          1   
282                      Cancer 8703; 58(12):2589-93          0   
299                      Cancer 8703; 58(12):2744-50          0   
...                                              ...        ...   
350107                 Transfusion 9112; 31(7):677-8          0   
350205                Kidney Int 9112; 39(6):1225-31          1   
350206                Kidney Int 9112; 39(6):1225-31          1   
350240          Public Health Rep 9112; 106(5):523-9          0   
350243          Public Health Rep 9112; 106(5):543-7          0   

           relevance_status                                       text_cleaned  
Unnamed: 0                                                                      
125            not_relevant  Prospective study liver function children foll...  
153            not_relevant  Postpartum thyroiditis--an underdiagnosed dise...  
222            not_relevant  Primary renal actinomycosis presence horseshoe...  
282                relevant  Clinical course breast cancer patients osseous...  
299            not_relevant  Cardiac abnormalities patients diffuse maligna...  
...                  

<350274x5000 sparse matrix of type '<class 'numpy.float64'>'
	with 21662129 stored elements in Compressed Sparse Row format>

## Exploring the data

In [5]:
tfidf_features.indices
tfidf_features.indptr
tfidf_features.format
tfidf_features.shape
tfidf_features.data

array([2790, 2328, 3239, ..., 3632,  667,  974])

array([       0,       54,      122, ..., 21661957, 21662021, 21662129])

'csr'

(350274, 5000)

array([0.2235799 , 0.07474592, 0.15994515, ..., 0.11581553, 0.06717378,
       0.04023658])

In [6]:
train_data['relevance_status'].unique()

array([nan])

## Converting 5000 features into a DataFrame

In [8]:
features = pd.DataFrame(tfidf_features.toarray())
features

0         1     2         3     4     5     6     7     8     9     \
0        0.0  0.000000   0.0  0.000000   0.0   0.0   0.0   0.0   0.0   0.0   
1        0.0  0.000000   0.0  0.000000   0.0   0.0   0.0   0.0   0.0   0.0   
2        0.0  0.126639   0.0  0.169046   0.0   0.0   0.0   0.0   0.0   0.0   
3        0.0  0.000000   0.0  0.000000   0.0   0.0   0.0   0.0   0.0   0.0   
4        0.0  0.000000   0.0  0.000000   0.0   0.0   0.0   0.0   0.0   0.0   
...      ...       ...   ...       ...   ...   ...   ...   ...   ...   ...   
350269   0.0  0.000000   0.0  0.000000   0.0   0.0   0.0   0.0   0.0   0.0   
350270   0.0  0.000000   0.0  0.000000   0.0   0.0   0.0   0.0   0.0   0.0   
350271   0.0  0.000000   0.0  0.000000   0.0   0.0   0.0   0.0   0.0   0.0   
350272   0.0  0.000000   0.0  0.000000   0.0   0.0   0.0   0.0   0.0   0.0   
350273   0.0  0.000000   0.0  0.000000   0.0   0.0   0.0   0.0   0.0   0.0   

        ...  4990  4991  4992  4993  4994  4995  4996  4997  4998  4999  
0       ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
1       ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2       ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3       ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
4       ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
...     ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  
350269  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
350270  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
350271  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
350272  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
350273  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  

[350274 rows x 5000 columns]

## Changing dtype to reduce memory usage

In [10]:
train_full = train_data[['sensitive']].join(features, how='left').astype('float32')
print('Train is joined')
valid_full = valid_data[['sensitive']].join(features, how='left').astype('float32')
print('Valid is joined')
test_full = test_data[['sensitive']].join(features, how='left').astype('float32')
print('Test is joined')

train_full

Train is joined
Valid is joined
Test is joined


sensitive    0    1    2        3    4    5    6    7    8  ...  \
Unnamed: 0                                                              ...   
55655             0.0  0.0  0.0  0.0  0.00000  0.0  0.0  0.0  0.0  0.0  ...   
277600            0.0  0.0  0.0  0.0  0.00000  0.0  0.0  0.0  0.0  0.0  ...   
172713            0.0  0.0  0.0  0.0  0.03247  0.0  0.0  0.0  0.0  0.0  ...   
277300            0.0  0.0  0.0  0.0  0.00000  0.0  0.0  0.0  0.0  0.0  ...   
132901            0.0  0.0  0.0  0.0  0.00000  0.0  0.0  0.0  0.0  0.0  ...   
...               ...  ...  ...  ...      ...  ...  ...  ...  ...  ...  ...   
125350            0.0  0.0  0.0  0.0  0.00000  0.0  0.0  0.0  0.0  0.0  ...   
271319            0.0  0.0  0.0  0.0  0.00000  0.0  0.0  0.0  0.0  0.0  ...   
137903            0.0  0.0  0.0  0.0  0.00000  0.0  0.0  0.0  0.0  0.0  ...   
153639            0.0  0.0  0.0  0.0  0.00000  0.0  0.0  0.0  0.0  0.0  ...   
127517            0.0  0.0  0.0  0.0  0.00000  0.0  0.0  0.0  0.0  0.0  ...   

            4990  4991  4992      4993  4994  4995  4996  4997  4998  4999  
Unnamed: 0                                                                  
55655        0.0   0.0   0.0  0.000000   0.0   0.0   0.0   0.0   0.0   0.0  
277600       0.0   0.0   0.0  0.254654   0.0   0.0   0.0   0.0   0.0   0.0  
172713       0.0   0.0   0.0  0.000000   0.0   0.0   0.0   0.0   0.0   0.0  
277300       0.0   0.0   0.0  0.000000   0.0   0.0   0.0   0.0   0.0   0.0  
132901       0.0   0.0   0.0  0.000000   0.0   0.0   0.0   0.0   0.0   0.0  
...          ...   ...   ...       ...   ...   ...   ...   ...   ...   ...  
125350       0.0   0.0   0.0  0.000000   0.0   0.0   0.0   0.0   0.0   0.0  
271319       0.0   0.0   0.0  0.000000   0.0   0.0   0.0   0.0   0.0   0.0  
137903       0.0   0.0   0.0  0.000000   0.0   0.0   0.0   0.0   0.0   0.0  
153639       0.0   0.0   0.0  0.000000   0.0   0.0   0.0   0.0   0.0   0.0  
127517       0.0   0.0   0.0  0.000000   0.0   0.0   0.0   0.0   0.0   0.0  

[284013 rows x 5001 columns]

## Trying different hyperparams

In [12]:
# Logistic regression model
X_train = train_full.drop(columns=['sensitive'])
y_train = train_full['sensitive']
X_valid = valid_full.drop(columns=['sensitive'])
y_valid = valid_full['sensitive']

# Checking the memory usage
X_train.info()

for max_it in tqdm([100, 500]):
    estimator = LogisticRegression(max_iter=max_it)
    estimator.fit(X_train, y_train)
    print('F-1 score for {} max_iters is {}'.format(max_it, fbeta_score(y_valid, estimator.predict(X_valid), beta=1)))

<class 'pandas.core.frame.DataFrame'>
Index: 284013 entries, 55655 to 127517
Columns: 5000 entries, 0 to 4999
dtypes: float32(5000)
memory usage: 5.3 GB


  0%|          | 0/2 [00:00<?, ?it/s]

LogisticRegression()

 50%|█████     | 1/2 [02:19<02:19, 139.24s/it]

F-1 score for 100 max_iters is 0.47124047124047125


LogisticRegression(max_iter=500)

100%|██████████| 2/2 [04:35<00:00, 137.61s/it]

F-1 score for 500 max_iters is 0.47124047124047125


Since there is no difference in metrics, it is more optimal to use 'lightweight' model with maximum amount of iterations equal to 100

## Testing the model on test data and calculating all the metrics

In [15]:
X_test = test_full.drop(columns=['sensitive'])
y_test = test_full['sensitive']

estimator = LogisticRegression(max_iter=100)
estimator.fit(X_train, y_train)
pred = estimator.predict(X_test)

results = pd.DataFrame(columns=['Precision', 'Recall', 'F-1', 'F-2', 'Accuracy'])
results.loc[0, 'Precision'] = precision_score(y_test, pred)
results.loc[0, 'Recall'] = recall_score(y_test, pred)
results.loc[0, 'F-1'] = fbeta_score(y_test, pred, beta=1)
results.loc[0, 'F-2'] = fbeta_score(y_test, pred, beta=2)
results.loc[0, 'Accuracy'] = accuracy_score(y_test, pred)

print('Resulting model perfomance:')
results

LogisticRegression()

Resulting model perfoamce:


Precision    Recall       F-1      F-2 Accuracy
0  0.834225  0.398366  0.539233  0.44485  0.91741